[project]
name = "comp214-group-project"
version = "1.0.0"
requires-python = ">=3.11,<3.14"
dependencies = ["backend"]

[tool.uv.sources]
backend = { workspace = true }

[tool.uv.workspace]
members = ["packages/backend"]
